spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}/${MONGODB_DATABASE}

jwt:
  accessKey: ${JWT_ACCESS_SECRET}
  refreshKey: ${JWT_REFRESH_SECRET}